### ISSUE TITLE
Display navbar issues with the mobile website

### ISSUE THREAD

**Issue by TSGut** [paleorXiv/paleorXiv.github.io#10]
The navbar isn't working in the mobile version (I've checked previous versions and there doesn't seem to be a point where it worked as intended), so I am opening this issue primarily to remind myself to check how to make the mobile website's navbar function properly in the coming week. 

I'm on it, just putting this here as a known issue for now.

**Comment by TSGut** [comment]
Found the error, the issue was in the way the pages were loading jquery (i.e. not at all :) ). It's odd behavior since this was based on a premade theme originally (did somebody have a reason to try and remove jquery?). 

I've added this fix to the pull request, merging will make the mobile navbar work as intended on phones, tablets and small screens. We can close this issue after merge.

**Comment by Protohedgehog** [comment]
Merged so can close this now.
