### ISSUE TITLE
Unify "Contact Us" approach, perhaps in its own Navigation tab

### ISSUE THREAD

**Issue by TSGut** [paleorXiv/paleorXiv.github.io#4]
At the moment the website uses a generic "contact us" footer on every page but also has various places in the website which link the email address and ask people to send emails. I think this is a bit too confusing non native internet users. 

Multiple equivalent ways to contact the project runners can confuse people because they may not at first glance realize they actually are equivalent. To this end, I think a lot of the contact options on each page should be removed and moved to a new clearly visible top bar navigation tab "Contact" or "Contact us" or "About" which gives details on how to contact the project runners or mods and what we should be contacted for (questions, suggestions, all the stuff that is currently spread across the site). 

I think a single strong "Contact Us" section would be very valuable. I think the steering committee list on the "Home" tab and all of those should then also be moved from the Home to the contact us page and the roles of the respective people should be made more clear since it's not transparent what each person does exactly.

**Comment by Protohedgehog** [comment]
OK, loads better now. Have a new tab, and deleted all the additional contact bits throughout: https://paleorxiv.github.io/contact_us.html

**Comment by TSGut** [comment]
Great, I think this will help people navigate the site quite a bit. Perhaps we should add a little short paragraph to the "email us" line explaining under what circumstances an email might be appropriate. Something like "If you have any questions regarding X or Y, feel free to send us an email", so that people don't feel like their kind of question is perhaps not desired.

**Comment by Protohedgehog** [comment]
OK, will get on that!
