### ISSUE TITLE
Unify "Code of Conduct" and "Diversity Statement"

### ISSUE THREAD

**Issue by TSGut** [paleorXiv/paleorXiv.github.io#5]
The navigation bar is a bit crowded at the moment, giving the impression of a lot of rules and regulations that apply when the actual process is rather simple on the end of the researcher. I think to combat this, the navigation tabs should be compressed and unified.

Specifically, I believe the Code of Conduct and Diversity Statement are close enough to each other in spirit that they can be framed under a single tab in the navigation bar. As for name suggestions, I believe "Code of Conduct" is general enough but it could be reformulated as "Our Standards" as well. The content could more or less just be a fusion of the current two pages with minor stylistic changes to make it work as a single page.

**Comment by Protohedgehog** [comment]
OK, one done! https://paleorxiv.github.io/code_of_conduct.html

**Comment by TSGut** [comment]
Great, don't forget to update the header on the other navigation tab pages too. At the moment there is still the dead link present on some of the other pages. Compare headers of https://paleorxiv.github.io/submission_guidelines.html and https://paleorxiv.github.io/index.html

**Comment by Protohedgehog** [comment]
Ah yes oops! Fixed now  (besides for the moderation tab, which I'll do next)

**Comment by TSGut** [comment]
https://paleorxiv.org still links to the diversity statement page that doesn't exist anymore and is now fused into code of conduct.

We can change that link so that it refers directly to the diversity statement section of the code of conduct page if you want (i.e. I can create a nice redirect). I would just have to create some internal labeling on the code of conduct page.

**Comment by Protohedgehog** [comment]
Ah, I see. I'll simply email the OSF about this and get them to point to a different link.
