### ISSUE TITLE
Unify Submission Guidelines tab with Moderation tab and clarify the rules pages

### ISSUE THREAD

**Issue by TSGut** [paleorXiv/paleorXiv.github.io#6]
The first question on the mind of the researcher when visiting this website will be "What can this do for me?". The second question, assuming the website sufficiently answers what it can do for the researcher is "So how does this work exactly?". I think that a lot of potential researchers who would in principle want to participate are lost in both steps and so both should be addressed in potential future updates to the site design.

At the moment "So how does this work exactly?" is answered in the "Submission Guidelines" and the "Moderation" tabs. One essentially deals with "what you have to do" and the other with "what we do with your submitted work". I think this spreads out the "So how does this work exactly?" information over two pages (three if you count Journal Policies, but that tab is a necessary evil in today's scientific landscape) when it probably should be on one only (meaning 1 + Journal policies).

To that end, I suggest fusing Moderation and the Submission guidelines into one tab which I would suggest simply calling "Submission" or perhaps even the current "Submission Guidelines". That new fused tab should be organized in a very clear two segment structure: 
a) The rules you need to follow 
and 
b) What we do once you have submitted your paper. 

As a first order solution fusing the moderation to the end of the current submission guidelines is a good start but I think we should probably think of making the whole submission process more clear. Specifically I think both the FAQ and the Submission Guidelines section should probably have "jump to headline" navigation somehow in the sense that Wikipedia also has it since that is a familiar website tool for most people, i.e. the different segments of those pages should be presented in a linked overview structure at the top of the page. I will look into how that might be implemented effectively.

**Comment by Protohedgehog** [comment]
OK, lemme work on that today, have to head out for a bit now though. Any idea how to do that jump to stuff? That would be very useful!

**Comment by TSGut** [comment]
Yep, I'll throw together a suggestion for that in a bit and you can see if you'd like to implement it.

**Comment by Protohedgehog** [comment]
Done! https://paleorxiv.github.io/submission_guidelines.html
