### ISSUE TITLE
Odd link structure in FAQ section

### ISSUE THREAD

**Issue by TSGut** [paleorXiv/paleorXiv.github.io#7]
Perhaps this is a leftover of some pre-migration setup or maybe it is intended to be used as navigation links but at the moment, the FAQ section has flat, dead links in their headers.

What I mean is that on https://paleorxiv.github.io/faq.html the separate question FAQ bits are links which for example link to https://paleorxiv.github.io/faq.html#faq2 which does not do anything. This is odd non-standard behavior and should probably be removed unless there is an intended future purpose for this?

I can remove it simply by removing the href in the html (I've done so in my fork) but I wanted to make sure this is an unintentional feature before submitting a pull request.

**Comment by Protohedgehog** [comment]
Ah, I think this is just a hangover from the migration too. Good spot, can be removed!

**Comment by TSGut** [comment]
Alright, I'll submit a pull request with the updated faq.html momentarily. Issue can be closed once that's done.
